---
- name: Playbook para crear el archivo de datos
  hosts: localhost
  become: true
  vars:
    nombre: Lucio
    apellido: Alcoba
    division: 116
    fecha: 12/12/24
    distro: Ubuntu
    cores: 6
  roles:
    - 2PRecuperatorio

- name: Crear usuarios y asignar grupos
  hosts: localhost
  become: true
  roles:
    - Alta_Usuarios_Alcoba

- name: Configurar sudoers para GProfesores
  hosts: localhost
  become: true
  roles:
    - Sudoers_Alcoba

- name: Instalar herramientas necesarias
  hosts: localhost
  become: true
  roles:
    - Instala-tools_Alcoba
